### ISSUE TITLE
How to add <track> or caption ? I want to add a .vtt file, but where to place ?

### ISSUE THREAD

**Issue by dipsraj** [xDae/react-plyr#17]

**Comment by vuuet** [comment]
I have the same question :)

**Comment by xDae** [comment]
at the moment is not possible to add tracks or captions, it will be available in the next release :)

**Comment by rubenswieringa** [comment]
This issue should now be resolved through PR #47, correct?

**Comment by xDae** [comment]
here you have the example how to add captions:
https://github.com/xDae/react-plyr/blob/master/.storybook/stories/index.js#L96
