### ISSUE TITLE
autoplay doesn't work if you change the url

### ISSUE THREAD

**Issue by benwaffle** [xDae/react-plyr#19]
If you have a `<Plyr url={...} autoplay={true} />`, and you change the URL, e.g. via `setState()`, then it becomes paused until you hit the play/pause button. It should automatically play the new media

**Comment by xDae** [comment]
Please, take a look to the new version of react-plyr, and comment here if you are having the issue again

**Comment by quaeched** [comment]
I'm using v2.2.0 and experiencing this issue.

**Comment by quaeched** [comment]
Got it working running `setTimeout ( () => @plyr.play() ), 50` (CoffeeScript) after changing source.
