### ISSUE TITLE
Issue with the packaged CSS file.

### ISSUE THREAD

**Issue by rgrandi** [xDae/react-plyr#2]
When installing the package through npm I get the following error message:

```
ERROR in ./~/plyr/dist/plyr.css
Module parse failed: /Users/richard/Documents/WP Engine/Indepen/wp-content/themes/indepen/node_modules/plyr/dist/plyr.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

It can be resolved by commenting out the CSS file and then putting it in my styles, but this is not ideal.

**Comment by xDae** [comment]
yes, you are right, styles should be loaded in the project, not in the component,

**Comment by rafaelderolez** [comment]
@xDae I see this has been fixed recently on the repo, but the issue still persists on the npm version. Could you please update it?

**Comment by xDae** [comment]
@rafaelderolez yes, I have fixed in master, let me create a new tag, cheers!

**Comment by xDae** [comment]
@rafaelderolez you have the a new version 😎

**Comment by omeraplak** [comment]
@xDae hi,
lib folder does not include css file. can you check it?
