### ISSUE TITLE
Video quality options (HTML5, YouTube, Vimeo) 

### ISSUE THREAD

**Issue by rafaelderolez** [xDae/react-plyr#24]
The official Plyr now supports [video quality options](https://github.com/sampotts/plyr/commit/3395e8df903cdd63e227a377b4b3be77da682aa8). Is it possible to add these to react-plyr?

**Comment by xDae** [comment]
Yes, we have pending a pr with the new version of plyr, so it should be integrated

**Comment by xDae** [comment]
Update the libray to support the latest Plyr version, comment here if you are having this issue again and we can reopen this issue :)
