### ISSUE TITLE
Styles and SVG

### ISSUE THREAD

**Issue by antonysastre** [xDae/react-plyr#25]
How are styles and the default svg-sprites meant to be used? Just rendering the component doesn't get the Plyr default styling. Is this by design?

**Comment by xDae** [comment]
do you mean how you can style the player?

just importing the css file:
``<link rel="stylesheet" href="https://cdn.plyr.io/3.2.4/plyr.css">``

**Comment by xDae** [comment]
https://github.com/xDae/react-plyr/issues/28
