### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by karanmartian** [xDae/react-plyr#26]
Hi, when will this support react 16?

**Comment by karanmartian** [comment]
thanks so when is the next release scheduled?

**Comment by xDae** [comment]
tomorrow i expect to release the new version, Im still implementing some new stuff

**Comment by schnubor** [comment]
That would be awesome, gogo @xDae !

**Comment by xDae** [comment]
@zamirkhan you have to import the styles separately, v2 with new docs are coming :)

**Comment by zamirkhan** [comment]
Great. Thank you! Looking forward to it.

**Comment by xDae** [comment]
I released a new version of React Plyr, take a look on it and test, feel free to report any problem:

https://github.com/xDae/react-plyr/releases

Im going to keep this issue open a few days until we can confirm its working fine for all the React Plyr users

**Comment by zamirkhan** [comment]
Awesome. Thank you! I have upgraded and will let you know if I see any issues.

**Comment by cefer** [comment]
All good for me, I'm using react 16.3.0 and react-plyr 2.0.1, but for the css version I'm using https://cdn.plyr.io/3.3.20/plyr.css instead of https://cdn.plyr.io/3.3.9/plyr.css"

@xDae thank you for your efforts!
