### ISSUE TITLE
Multiple players on same page

### ISSUE THREAD

**Issue by zamirkhan** [xDae/react-plyr#27]
How can we dynamically create multiple players on the same page? Say I have an array of video urls and want to create a Plyr for each. I would do something like this:

```        
{[
          "https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4",
          "https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4",
          "https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4"
        ].map(v => (
          <div style={{ width: "320px", height: "180px" }}>
          <Plyr
            url={v}
            type="video"/>
          </div>
        ))}
```

But in this scenario it appears only the first player will become initialized. The others are simply images (and also don't appear to behave, CSS-wise).

<img width="682" alt="screen shot 2018-05-16 at 9 22 29 am" src="https://user-images.githubusercontent.com/2654175/40119475-d218967e-58ea-11e8-9795-bc67f2d942d8.png">

There appears to be some special handling required for multiple players in Plyr: https://github.com/sampotts/plyr#setting-up-multiple-players

**Comment by zamirkhan** [comment]
As a workaround, it appears that if each player is assigned a unique className, then it works.

**Comment by xDae** [comment]
so, having an unique classname for each player works ?

**Comment by zamirkhan** [comment]
Yes, in my case that is working. I basically did something like this:

`className={"react-plyr-" + someUniqueIdentifier}`

and that resolves it.

**Comment by xDae** [comment]
Im going to add also that case to the demos ;)

**Comment by 23twenty** [comment]
Please add this to the docs! Spent a few hours before I realized this was the issue lol
