### ISSUE TITLE
Access to methods

### ISSUE THREAD

**Issue by rafaelderolez** [xDae/react-plyr#3]
I might be completely missing something but how does one use the plyr methods? 
I'd want to stop a player when closing a modal.

**Comment by xDae** [comment]
Hi @rafaelderolez, I'm rewriting the component to expose all the original methods from Plyr to the "react way".

it should be ready in a few days, thanks for the comments, I will work on that this days

**Comment by rafaelderolez** [comment]
@xDae Awesome! Will you do the events as well? It would be very useful in my usecase to have the my modal auto close when the video ends.

**Comment by xDae** [comment]
@rafaelderolez yes, you could call the onEnd prop to know if the video has finished and do whatever you want 😉 

onPlay: PropTypes.func,
onPause: PropTypes.func,
onEnd: PropTypes.func,
onSeeked: PropTypes.func,
onEnterFullscreen: PropTypes.func,
onVolumeChange: PropTypes.func,

**Comment by xDae** [comment]
@rafaelderolez in the 1.3.0 there are some methods exposed, let me know if you try to close the issue 

cheers!
