### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by AllanPooley** [xDae/react-plyr#31]
Hey Jose, 

Started using this wrapper for a build just today - thanks for putting time into building and maintaining it.

It works great for me, but when my colleague pulled down my changes he was hit with the following error:

```
/Users/{user}/localhost/{project}/node_modules/react-plyr/lib/defaultProps.js:95
   language: (navigator.language || navigator.userLanguage).split('-')[0]
              ^
ReferenceError: navigator is not defined
```

For context, the code lives here in `react-plyr/lib/defaultProps.js`:
```
// Captions settings
  captions: {
    active: false,
    language: (navigator.language || navigator.userLanguage).split('-')[0]
  }
```

https://developer.mozilla.org/en-US/docs/Web/API/Navigator

Any ideas why this might be occurring for him?

**Comment by AllanPooley** [comment]
Could be an issue with Server Side Rendering. Possible fallback solution:
 
```
export function getInterfaceLanguage() {
  const defaultLang = 'en-US';
  if (typeof navigator === "undefined") {
    return defaultLang;
  }
  if (!!navigator && !!navigator.language) {
    return navigator.language;
  } else if (!!navigator && !!navigator.languages && !!navigator.languages[0]) {
    return navigator.languages[0];
  } else if (!!navigator && !!navigator.userLanguage) {
    return navigator.userLanguage;
  } else if (!!navigator && !!navigator.browserLanguage) {
    return navigator.browserLanguage;
  }
  return defaultLang;
}
```

Credit to @stefalda https://github.com/stefalda/react-localization/blame/65c882b6c4bfaceb57575f2c9c0ae639b16c4521/src/utils.js#L2-L16

**Comment by AllanPooley** [comment]
I went to make a pull request and I see this has been already fixed in https://github.com/xDae/react-plyr/pull/30 !

I'll apply the fix above!

**Comment by xDae** [comment]
Hi @AllanPooley, as you mentioned, the fix is already merged to master, Im going to release a new patch version hopefully today

**Comment by Coriou** [comment]
Hey guys,

Any update on this issue ? Trying to build with Gatsby and without touching this library, I had to defer the loading of Plyr to avoid server side rendering which is a bit of shame.

Thanks
