### ISSUE TITLE
Latest Release 2.1.0 is Broken

### ISSUE THREAD

**Issue by brandoneggar** [xDae/react-plyr#37]
Release 2.1.0 is BROKEN.

Steps to reproduce:
* Create sample app using create-react-app
* yarn add react-plyr
* import Plyr from 'react-plyr' in project and try to run app.

Issue:

If you look under node_modules/react-plyr the src code for the lib is missing.

There's only 3 files in there:
* LICENSE
* package.json
* README.md

**Comment by frogg** [comment]
Yep, similar issues here:

`Module not found: Can't resolve 'react-plyr'`

**Comment by xDae** [comment]
new 2.1.1 version released ;)
