### ISSUE TITLE
Example of playing and pausing the video

### ISSUE THREAD

**Issue by amilajack** [xDae/react-plyr#44]
Can someone please post an example of using the [api's listed here](https://github.com/xDae/react-plyr/blob/master/src/index.js#L123-L124) to programmatically pause and play? Thanks!

**Comment by xDae** [comment]
You can check how is done in this example: https://xdae.github.io/react-plyr/?selectedKind=React%20Plyr&selectedStory=External%20Controls%20%26%20State&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

https://github.com/xDae/react-plyr/blob/master/.storybook/stories/withWrapper.js

**Comment by amilajack** [comment]
thanks!
