### ISSUE TITLE
Poster element not getting created

### ISSUE THREAD

**Issue by xavianaxw** [xDae/react-plyr#45]
`react-plyr` version : `2.1.1`

Simple setup with `currentVideo` in my state with the following properties

```
{
        id: 1,
        title: "Building a more inclsuive future for Australia",
        short_title: "Making a change",
        excerpt: "London Suicide Bombing Survivor",
        thumbnail: [image_url],
        videoId: "JYbooGL_Dbc",
}
```

and my component

```
<Plyr
          provider="youtube"
          videoId={currentVideo.videoId}
          poster={currentVideo.thumbnail}
          controls={plyrOptions.controls}
          fullscreen={plyrOptions.fullscreen}
          ref={this.player}
          debug
        />
```

Here's the end rendering without the poster element

![screen shot 2018-08-24 at 6 51 42 pm](https://user-images.githubusercontent.com/8082158/44575177-c41aea80-a7ce-11e8-94d0-4cb1a53d0aae.png)

**Comment by xDae** [comment]
poster is not compatible with the youtube video type

**Comment by xavianaxw** [comment]
Oh but it works on Plyr? If is not supported then this isnt an issue then
