### ISSUE TITLE
Error upon hiding component through conditional rendering

### ISSUE THREAD

**Issue by rubenswieringa** [xDae/react-plyr#56]
*(This case is pretty straight-forward, but if you would like a working example let me know)*

---

With the following code:

```js
render () {
  let player;
  if ( this.props.includePlayer ) player = <Plyr provider="youtube" videoId="5Sbbiv5iSiQ" />;
  return player || null;
  );
}
```

When `render()` is called while `includePlayer` is `true` and then `false` respectively, then the latter call will trigger the following 2 errors:

<details>
 <summary>Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.</summary>

* at removeChildFromContainer (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:8727:15)
* at unmountHostComponents (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:16471:9)
* at commitDeletion (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:16519:5)
* at commitAllHostEffects (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:17214:11)
* at HTMLUnknownElement.callCallback (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:149:14)
* at Object.invokeGuardedCallbackDev (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:199:16)
* at invokeGuardedCallback (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:256:31)
* at commitRoot (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:17423:7)
* at completeRoot (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18912:3)
* at performWorkOnRoot (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18841:9)

The above error occurred in the <Plyr> component:
* in Plyr (created by VideoDisplay)
* in VideoDisplay (created by Connect(VideoDisplay))
* in Connect(VideoDisplay) (created by App)
* in App
* in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
</details>

<details>
 <summary>Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.</summary>

* at Object.invokeGuardedCallbackDev (react-dom.development.js:210)
* at invokeGuardedCallback (react-dom.development.js:256)
* at commitRoot (react-dom.development.js:17423)
* at completeRoot (react-dom.development.js:18912)
* at performWorkOnRoot (react-dom.development.js:18841)
* at performWork (react-dom.development.js:18749)
* at performSyncWork (react-dom.development.js:18723)
* at requestWork (react-dom.development.js:18592)
* at scheduleWork (react-dom.development.js:18401)
* at Object.enqueueSetState (react-dom.development.js:12313)
</details>

---

Any ideas on how to fix/work around this?

**Comment by xDae** [comment]
try with the new version of the package ;)

**Comment by soostamas** [comment]
I'm having the same issue with the new version :/
