### ISSUE TITLE
Setting currentTime

### ISSUE THREAD

**Issue by jhalvorson** [xDae/react-plyr#58]
Hi, 

How can I set the currentTime on componentDidMount?

I've tried: `this.video.setCurrentTime(<number>)` but it throws: `Uncaught TypeError: _this.video.setCurrentTime is not a function`.

Thanks!

**Comment by xDae** [comment]
sorry for the delay, the new release is out, could you check it and close this issue if it works?

thanks!

**Comment by manuf10** [comment]
Hello @jhalvorson, could you solve this?

**Comment by quaeched** [comment]
Checked. Works perfectly. Make sure You're using the right reference, i.e. `​ref={(plyr) => this.plyr = plyr}` in the component and then `this.plyr.setCurrentTime(<number>)` in the code ;)

**Comment by xDae** [comment]
closing this issue then, I will document this in the README
